project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Ivan Pozdniakov"
  page-footer:
    left: "&copy; 2026 Ivan Pozdniakov"
    right:
      - icon: github
        href: https://github.com/Pozdniakov
      - icon: telegram
        href: https://t.me/pozdniakovivan
      - icon: envelope
        href: mailto:ivanspozdniakov@gmail.com

format:
  html:
    theme: darkly
    css: styles.css
    toc: false

editor: visual
